#  Copyright (c) 2012-2018, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

# Settings relevant for the hitobito_sbv wagon
# Overrides settings from the main application
application:
  logo:
    image: logo-sbv.svg
    width: 200
    height: 60
    background_color: white

  languages:
    de: Deutsch
    fr: Fran√ßais
    it: Italiano
  additional_languages:
    rm: Rumantsch

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito@puzzle.ch

census:
  default_finish_month: 11
  default_finish_day: 30

pdf:
  font_size: 8

messages:
  enable_writing: true

assignments:
  enabled: true
